---
# tasks file for postgresql
- name: install postgresql
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present 
    update_cache: true

- name: enable service postgresql
  service: 
    name: postgresql
    state: started
    enabled: true

- name: find directory postgresql config
  find:
    paths: /etc/postgresql
    recurse: true
    patterns: 'postgresql.conf'
  register: pg_conf_result

- name: set variable for postgresql config directory 
  set_fact:
    # Берем путь первого найденного файла и отрезаем само имя файла, оставляя путь к папке
    pg_config_path: "{{ pg_conf_result.files[0].path | dirname }}"

- name: Configure PostgreSQL to listen on all network interfaces
  lineinfile: 
    path: "{{ pg_config_path }}/postgresql.conf"
    regexp: '^#?listen_addresses'
    line: "listen_addresses = '*'"
  notify: restart postgresql

- name: Grant access to DB for web servers
  community.postgresql.postgresql_pg_hba:
    dest: "{{ pg_config_path }}/pg_hba.conf"
    contype: host
    databases: "{{ postgres_db_name }}"
    users: "{{ postgresql_db_user }}"
    address: "{{ hostvars[item]['ansible_host'] }}/32"
    method: md5
  loop: "{{ groups['web_servers'] }}"
  notify: restart postgresql
  become: true
  become_user: postgres

- name: create database
  community.postgresql.postgresql_db:
    name: "{{ postgres_db_name }}"
  become: true
  become_user: postgres

- name: Create database user
  community.postgresql.postgresql_user:
    name: "{{ postgresql_db_user }}"
    password: "{{ postgresql_db_pass }}"
  become: true
  become_user: postgres

- name: Grant ALL privileges on database to user
  community.postgresql.postgresql_privs:
    db: "{{ postgres_db_name }}"
    role: "{{ postgresql_db_user }}"
    objs: "{{ postgres_db_name }}"
    type: database
    privs: ALL
  become: true
  become_user: postgres

- name: allow postgresql port in UFW for group web_servers
  ufw:
    rule: allow
    port: 5432
    proto: tcp
    from_ip:  "{{ hostvars[item]['ansible_host'] }}"
  loop: "{{ groups['web_servers'] }}"
