---
- name: Install PostgreSQL packages
  import_tasks: install.yml

- name: Configure PostgreSQL networking and security
  import_tasks: config.yml

- name: Manage Databases and Users
  import_tasks: database.yml
  become: true
  become_user: postgres

- name: allow postgresql port in UFW 
  import_tasks: firewall.yml
  tags: [ 'network', 'security' ]




