---
- name: Install nginx 
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default nginx config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Allow HTTPs traffic
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '80'
    - '443'

- name: Start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes