- name: Configure infrastructure
  hosts: all
  become: true

  roles:
#    - common
#    - docker
    - web_apps
    - nginx 
    - ssl_certs_cloudflare
#    - virtual_hosting
    - load_balancer
