- name: configure infrastructure db
  hosts: db_servers
  become: true
  gather_facts: true

  roles:
  - common
  - postgresql 

- name: Configure infrastructure web
  hosts: web_servers
  become: true

  roles:
    - common
    - docker
    - web_apps
    - nginx 
    - ssl_certs_cloudflare
    - virtual_hosting
#    - load_balancer



