ssh_port: 2222
ansible_port: "{{ ssh_port }}"
ansible_user: "{{ my_user }}"
my_user: madmin1

domain_name: "cloudtests.work"
admin_email: "bursv1994serja@gmail.com"

postgres_db_name: "projectname_prod"
postgresql_db_user: "projectname_user"