---
- name: Ensure backup directory exists 
  file:
    path: "{{ backup_postgres_path }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0755'
  

- name: Deploy backup script
  template:
    src: postgres_backup.sh.j2
    dest: "/usr/local/bin/{{ backup_postgres_script_name }}" 
    owner: postgres
    group: postgres
    mode: '0755'

- name: Setup Cron job for database backup
  ansible.builtin.cron:
    name: "Backup for {{ backup_postgres_db_name }}"
    user: postgres
    hour: "{{ backup_postgres_hour }}"
    minute: "{{ backup_postgres_minute }}"
    job: "/usr/local/bin/{{ backup_postgres_script_name }}" 

