---
- name: Configurete SSH config 
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
    state: present
    validate: '/usr/sbin/sshd -t -f %s'
  loop:
    - { regexp: '^#?Port' , line: "Port {{ssh_port}}" }
    - { regexp: '^#?PermitRootLogin' , line: 'PermitRootLogin no' }
    - { regexp: '^#?PasswordAuthentication' , line: 'PasswordAuthentication no' }
    - { regexp: '^#?Include /etc/ssh/sshd_config.d/*.conf' , line: '# Include /etc/ssh/sshd_config.d/*.conf' }
  notify: restart ssh