---
- name: install_docker
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - ca-certificates
    - curl
    - gnupg
    - software-properties-common

- name: create directory for key
  file:
    path: "{{docker_gpg_keyrings_dir}}"
    state: directory
    mode: '0755'

- name: copy_docker_gpg_keyrind
  get_url:
    src: "{{docker_gpg_url}}"
    dest: "{{docker_keyring_path}}"

- name: add docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by={{docker_keyring_path}}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: istall docker
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: add_user_to_group_docker
  user:
    name: "{{my_user}}"
    groups: docker
    append: yes