---
- name: install certbot and cloudflare plugin
  apt:
    name: 
      - certbot
      - python3-certbot-dns-cloudflare
    state: present
    update_cache: yes
 
- name: create cloudflare ini file
  template:
    src: cloudflare.ini.j2
    dest: /root/.cloudflare.ini
    mode: '0600'

- name: Generate Wildcard SSL certificate
  command: >
    certbot certonly
    --dns-cloudflare
    --dns-cloudflare-credentials /root/.cloudflare.ini
    -d {{ domain_name }}
    -d "*.{{ domain_name }}"
    --non-interactive
    --agree-tos
    --email {{ admin_email }}
  args:
    creates: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"