---
 - name: remove htop, create directory and file
   hosts: all
   become: yes
   tasks:
   - name: remove htop
     apt:
       name: htop
       state: absent
   - name: create directory
     file:
       path: /tmp/ansible_test
       state: directory
       owner: root
       group: root
       mode: '0755'
   - name: create one more file
     copy:
       dest: /tmp/ansible_test/success.txt
       content: "Ansible script completed successfully"
       owner: root
       group: root
       mode: '0644'
